services:
  smartle:
    build:
      context: .
      dockerfile: Dockerfile
    image: cbl-option-b:jazzy
    platform: linux/amd64
    container_name: turtlebot3_container
    ports:
      - "5901:5901"
      - "8080:8080"
    volumes:
      - .:/ws/src/cbl_option_b
    environment:
      TURTLEBOT3_MODEL: burger
      ROS_DOMAIN_ID: "36"
      DISPLAY: ":1"
      LIBGL_ALWAYS_SOFTWARE: "1"
      VNC_RESOLUTION: "1280x800"
    stdin_open: true
    tty: true
    command: bash -lc "start-vnc && tail -f /dev/null"
